// list
export const ADD_TODO_INIT = 'ADD_TODO_INIT';
export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO_INIT = 'DELETE_TODO_INIT';
export const DELETE_TODO = 'DELETE_TODO';

// notifications
export const ADD_NOTIFICATION_INIT = 'ADD_NOTIFICATION_INIT';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATIONS_INIT = 'DELETE_NOTIFICATIONS_INIT';
export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';

